# Use the base image
FROM node:18.15.0-alpine

# Set the working directory inside the container
WORKDIR /usr/app

# Copy the entire current directory to the working directory in the container
COPY . .

# Install development dependencies using the package.json and package-lock.json files
RUN npm install

# Set environment variables
ENV NODE_ENV=development

# Set the command to run when the container starts
CMD ["npm", "run", "dev"]